# name: CI

# on: [push]

# jobs:
#   test:
#     name: Running Units Test
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1
#       - name: Run a one-line script
#         run: echo Hello, world!
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

name: CI JOB

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
      - name: run Build
        run: npm run build
